@extends('layouts.app')

@section('content')
<section class="hero" id="hero">
        <img src="{{url('/assets/img/hero.jpg')}}" alt="">
        <div class="container">
            <div class="hero-content">
                <div class="right-side">
                    <h3>Siap menjadi bagian dari IAKN Tarutung ?</h3>
                    <p>Daftar sekarang. Klik tombol di bawah  </p>
                    <a href="daftar">Daftar</a>
                </div>
                <div class="left-side">
                </div>
            </div>
            <div class="nav">
                <a href="alur"> <span>Alur Pendaftaran</span></a>
                <a href="pengumuman"><span>Pengumuman</span></a>
                <a href="uang-kuliah"><span>Uang Kuliah</span></a>
                <a href="program-studi"><span>Program Studi</span></a>
            </div>
        </div>
    </section>
    <section>
        <div class="container notif">
            <div class="box-notif">
                <p>Brosur pendaftaran online dan offline</p>
                <a href="/pdf/Brosur PMB IAKN Tarutung Tahun 2022.pdf" download>Download</a>
            </div>
        </div>
    </section>
    <section class="sejarah" id="sejarah">
        <div class="container">
            <h3>Sejarah IAKN Tarutung</h3>
            
            <div class="sejarah-box cf">
                <img src="{{url('/assets/img/hero.jpg')}}" alt="">
                <p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline; margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px; font-weight: bold;">Tarutung &ndash; Sumatera Utara</strong></p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">PGAKP Negeri Tarutung awalnya berasal dari sekolah Pendidikan Guru Agama Atas Kristen/Protestan (PGAA) dengan status Swasta yang berdiri sekitar tahun 1968 di Sigompulon &ndash; Tarutung. Menurut informasi dari beberapa orang yang dapat dipercaya bahwa pendirian sekolah ini diprakarsai oleh beberapa orang Kristen yang memberi perhatian terhadap pendidikan agama Kristen bersama dengan pemerintah. Sekolah ini mendidik calon-calon tenaga Guru Agama Kristen yang memiliki kemampuan mengajar di sekolah dasar dan sekolah lainnya. Sekitar tahun 1970 PGAAP diserahkan kepada pemerintah untuk mengelolanya, maka sekolah ini berubah status dari swasta menjadi Negeri. Pemerintah membangun gedung baru dan sarana belajar dilokasi yang baru ber-alamat di jalan Raja Saul Lumbantobing No.108 Tarutung. Sekitar tahun 1971 lokasi belajar pindah dari Sigompulon &ndash;Tarutung menempati gedung yang baru dipergunakan menjadi tempat belajar siswa PGAAP. Lokasi sekolah yang baru ini sangat terbatas sehingga ruangan belajar tidak cukup memadai untuk menampung siswa yang berkeinginan belajar di PGAAP, maka sekitar tahun 1975 ditemukanlah lokasi sekolah yang lebih luas beralamat di jalan Pemuda Ujung-Tangsi No. 17 Tarutung di tempat yang baru ini dibangunlah gedung sekolah yang memadai, gedung perkantoran, ruangan aula dan rumah dinas. Dan fasilitas lainnya. Setelah selesai pembangunan dilaksanakan sekitar tahun 1977 tempat yang baru ini dipergunakan sebagai tempat belajar,sedangkan gedung sekolah lama yang berada di jalan Raja Saul Lumbantobing No.108 Tarutung dipergunakan menjadi Asrama Putri. Menurut informasi dari beberapa orang yang dapat dipercaya sekolah ini sudah beberapa kali berubah nama antara lain:</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Para siswa di PGAKP Negeri Tarutung adalah lulusan dari SLTP/SMP. Lulusan dari sekolah ini kemudian yang menjadi tenaga Guru Agama Kristen Protestan pada sekolah Dasar (SD). Dalam kenyataan tamatan sekolah inilah pada umumnya yang diangkat oleh pemerintah dengan status Pegawai Negeri Sipil (PNS) menjadi Guru Agama Kristen Protestan pada sekolah-sekolah SD khususnya di wilayah Sumatera Utara dan di beberapa tempat di Indonesia.Pendidikan Guru Agama Atas Kristen / Protestan (PGAAP) status swastaPendidikan Guru Agama Atas Kristen / Protestan (PGAAP) status NegeriPendidikan Guru Agama Kristen Protestan (PGAKP) Negeri (Sumber Sejarah PGAK : Drs.Belvin Hutabarat salah seorang mantan Guru di PGAK dan M.Nainggolan mantan KTU dan Bendahara PGAA)</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Kemudian muncul kebijakan pemerintah dibidang pendidikan dengan diterbitkannya Undang-undang Nomor 2 Tahun 1989 tentang Sistim Pendidikan Nasional. Salah satu perubahan dalam pendidikan yang diakibatkan oleh undang-undang ini adalah bahwa yang menjadi tenaga Guru pada sekolah dasar minimal kualifikasi pendidikannya Diploma. Maka konsekuensinya seluruh sekolah keguruan setingkat SLTA ditutup antara lain SPG, SGO dan PGAKP.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">PGAKP Negeri Tarutung ditingkatkan menjadi LPTK-PAK Negeri Tarutung</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Sebelum PGAKP Negeri Tarutung ditutup, maka pengelola PGAKP Negeri Tarutung membuat perencanaan untuk mendirikan suatu lembaga pendidikan yang menyediakan tenaga Guru Agama Kristen Protestan yang dapat menyelenggarakan program Diploma. Persiapan untuk itu maka didirikanlah suatu lembaga yang disebut Lembaga Pendidikan Tenaga Keguruan &ndash; Pendidikan Agama Kristen (LPTK-PAK) Negeri, Lembaga ini didirikan berdasarkan surat keputusan Menteri Agama RI No. 179 Tahun 1990, tanggal 15 Augustus 1990, dan surat Dirjen Bimas Kristen Protestan No.:F/101/2364/1991, tanggal 26 Augustus 1991. Kemudian pada tanggal 16 September 1991 LPTK-PAK Negeri Tarutung diresmikan oleh Dirjen Bimas Kristen Protestan Departemen Agama RI di Gedung Nasional-Tarutung yang dihadiri oleh Bupati Tapanuli Utara beserta Unsur Muspida, Pimpinan Gereja, Tokoh masyarakat Tapanuli Utara, pimpinan Instansi beserta masyarakat Tapanuli Utara. Acara peresmian ini dipimpin oleh salah seorang Dosen LPTK PAK Negeri Tarutung yaitu bapak Pdt. W.T.P.Simarmata, MA, sebagai protokol dan acara kebaktian dipimpin oleh Bapak Pdt.Dr. M.O.Tampubolon yang juga sebagai salah seorang dosen di LPTK-PAK Negeri Tarutung.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Pada tahun 1991 LPTK-PAK Negeri Tarutung menerima mahasiswa baru Jurusan Pendidikan Agama Kristen (PAK) untuk program Diploma dua (D.2), sebanyak 100 orang program Diploma tiga (D.3) sebanyak 100 orang dan untuk program Strata satu (S.1) sebanyak 300 orang. Kemudian muncullah pergumulan baru mengenai nama perguruan tinggi menggantikan LPTK-PAK Negeri Tarutung, sebab LPTK-PAK bukanlah nama perguruan Tinggi sesuai dengan UU Sisdiknas No.2 Tahun 1989, tetapi merupakan wadah atau lembaga yang mempersiapkan sebuah Perguruan Tinggi Tenaga kependidikan untuk Agama Kristen. Sebab menurut Sisdiknas bahwa Pendidikan Tinggi dapat berbentuk Akademi, Politeknik , Sekolah Tinggi, Institut atau Universitas.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">LPTK-PAK Negeri Tarutung menjadi APGAKP Negeri Tarutung. Akhirnya Pemerintah memberikan perguruan tinggi mengganti LPTK-PAK setingkat Akademi dengan nama Akademi Pendidikan Guru Agama Kristen Protestan disingkat dengan (APGAKP) Negeri Tarutung. Akademi ini berdiri berdasarkan Surat Keputusan Menteri Agama RI nomor 58 A tahun 1993, tanggal 27 Pebruari 1993. Dengan keluarnya surat Keputusan MenteriAgama tersebut maka dengan sendirinya LPTK-PAK Negeri Tarutung ditutup dan diganti menjadi APGAKPN Tarutung.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Sesuai dengan ketentuan dalam Sisdiknas nomor 2 tahun 1989 &ldquo;Akademi merupakan perguruan tinggi yang menyelenggarakan pendidikan terapan dalam satu cabang atau sebagian cabang ilmu pengetahuan, teknologi atau kesenian tertentu. Akademi dan politeknik menyelenggarakan pendidikan professional&rdquo;. Berdasarkan ketentuan tersebut APGAKPN Tarutung hanya dapat menyelenggarakan pendidikan professional yaitu Program Diploma, tidak dapat menyelenggarakan Program Akademik Strata satu (S.1) Mahasiswa pada program Diploma dari LPTK-PAK yaitu D.2 dan D.3 otomatis menjadi mahasiswa APGAKPN Tarutung.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline; margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Mahasiswa Program S.1 pada LPTK-PAK Negeri Tarutung dialihkan menjadi Mahasiswa IAKM Kampus Tarutung. Muncullah persoalan baru menyangkut mahasiswa program S.1 yang sudah diterima pada LPTK-PAK Negeri Tarutung. Persoalannya adalah Program S.1 tidak ada pada APGAKP Negeri Tarutung, lalu bagaimana dengan mahasiswa program S.1 yang diterima pada LPTK-PAK Negeri Tarutung yang jumlahnya sekitar 300 orang . Pimpinan APGAKP Negeri Tarutung berkonsultasi dengan Dirjen Bimas Kristen Protestan Departemen Agama di Jakarta untuk penyelesaian masalah ini. Jalan keluar penyelesaiannya adalah bahwa mahasiswa Program S.1, yang sudah sempat diterima pada LPTK-PAK Negeri Tarutung dialihkan menjadi mahasiswa Institut Agama Kristen Medan (IAKM) kampus Tarutung berdasarkan surat Dirjen Bimas Kristen Protestan Dep. Agama RI No.: F/PP.00.9/128/1373/1993 Dari APGAKP Negeri Tarutung menjadi STAKPN Tarutung Sejalan dengan upaya mencerdaskan kehidupan bangsa dan meningkatkan kualitas sumber daya manusia Indonesia khususnya dibidang pendidikan dalam rangka pemberdayaan peserta didik, pemenuhan kebutuhan tenaga kependidikan pada pendidikan tingkat dasar, menengah dan tinggi baik negeri maupun swasta, serta pemenuhan kebutuhan Gereja/Umat Kristen Protestan dalam bidang keagamaan (rohaniwan) Instansi Pemerintah / Swasta, Bintal ABRI dan lain sebagainya, terutama di wilayah berpenduduk mayoritas Kristen, maka APGAKPN Tarutung yang hanya dapat menyelenggarakan program pendidikan D.2 dan D.3., tidak cukup memadai untuk memenuhi kebutuhan tenaga guru agama Kristen Prot&not;estan yang semakin berkembang, khususnya di wilayah Indonesia Barat, diperlukan pendidikan Tinggi yang dapat menyelenggarakan Program Sarjana (S.1) dan Pasca sarjana S.2 dan S.3. Perguruan tinggi yang dapat menyelenggarakan program tersebut adalah minimal Perguruan Tinggi setingkat Sekolah Tinggi, Institut atau Universitas.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Para pengelola APGAKPN Tarutung bekerjasama dengan Masyarakat, Gereja, dan Pemerintah Kabupaten Tapanuli Utara berusaha meningkatkan APGAKPN Tarutung menjadi Sekolah Tinggi. Keinginan itu dituangkan dalam bentuk surat rekomendasi yang disampaikan kepada Menteri Agama RI.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Surat rekomendasi tersebut adalah :</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Surat Rekomendasi dari Ephorus HKBP No.:355/L02/IX/1998, tanggal 9 September 1998.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Surat Rekomendasi dari Ketua Dewan Perwakilan Rakyat Daerah (DPRD) Tapanuli Utara No.:170/595/DPRD II/98, tanggal 12 September 1998.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Surat Rekomendasi dari Kakanwil Departemen Agama Provinsi Sumatera Utara No.:Wb/6-c/PP.032/2265/1998, tanggal 22 September 1998.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Keinginan itu terwujud dengan terbitnya Keputusan Presiden RI Nomor 19 Thn 1999, tanggal 3 maret 1999, tentang pendirian Sekolah Tinggi Agama Kristen Protestan Negeri (STAKPN) Tarutung. Surat Keputusan tersebut ditindaklanjuti dengan keluarnya Surat Keputusan Menteri Agama RI Nomor 83 Tahun 1999, tanggal 29 maret 1999, tentang Organisasi dan Tata Kerja Sekolah Tinggi Agama Kristen Protestan Negeri Tarutung. STAKP Negeri Tarutung dipercayakan menyelenggarakan Program Pendidikan akademik dan professional yaitu program Diploma dua (D.2), Diploma tiga (D.3) dan Strata satu (S.1), dengan empat jurusan, yaitu: Jurusan Pendidikan Agama Kristen (PAK), Jurusan Teologi, Jurusan Pastoral Konseling, Jurusan Musik Gerejawi.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Pada Tanggal 29 Mei 1999 Menteri Agama RI meresmikan Sekolah Tinggi Agama Kristen Protestan Negeri (STAKPN) Tarutung bertempat di Gedung Kesenian/Sopo Partungkoan Tarutung. Peresmian ini dihadiri Bupati dan unsur Muspida Tapanuli Utara, Pimpinan instansi pemerintah dan swasta, Pimpinan Gereja, tokoh agama, tokoh masyarakat dan masyarakat Tapanuli Utara. Mahasiswa STAKPN Tarutung adalah mahasiswa program D.2 dan D.3 dari APGAKP Negeri Tarutung yang sudah ditingkatkan menjadi STAKPN Tarutung. Pada Tahun itu juga, Tahun Akademi 1999/2000 STAKPN Tarutung menerima Mahasiswa Baru untuk 2 (dua) jurusan yaitu: Jurusan Pendidikan Agama Kristen : (PAK) (Program Diploma Dua (D.2), Program Diploma Tiga (D.3), Program Strata Satu (S.1). Jurusan Teologi: Program Strata Satu (S.1)</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Pada tahun akademik 2003/2004 Jurusan Pendidikan Musik Gerewi (PMG) menerima mahasiswa baru untuk Program Diploma Tiga (D3). Kemudian pada tahun 2006 jurusan ini menerima mahasiswa baru untuk Program S.1. Pada Tahun akademik 2006/2007 Jurusan Pastoral Konseling menerima mahasiswa baru untuk program S.1. selanjutnya STAKPN Tarutung membuka 4 jurusan Program Strata-I yaitu : Jurusan Pendidikan Agama Kristen (Strata-I), Jurusan Teologi (Strata-I), Jurusan Pastoral Konseling (Strata-I), dan Jurusan Pendidikan Musik Gerejawi (Strata-I). Selanjutnya di Tahun 2013, STAKPN Tarutung dengan Ijin Dirjen Bimas Kristen Kementerian Agama RI telah membuka Program Pascasarjana untuk Jurusan Pendidikan Agama Kristen.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Sebagai salah satu syarat untuk peningkatan status STAKPN Tarutung menjadi Institut Agama Kristen Negeri (IAKN) Tarutung adalah jumlah jurusan yang dibuka pada lembaga tersebut. Maka pada tahun 2014, STAKPN Tarutung dengan segala upaya dan daya yang dimiliki mencoba membuka program jurusan Terapan dalam rangka memenuhi kebutuhan stakeholders. Adapun jumlah jurusan ahli terapan yang tambah adalah 5 jurusan. Sehingga jumlah jurusan yang dibuka di STAKPN Tarutung adalah :</p>
<ol style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px 35px; padding: 0px; list-style: decimal; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">
    <li style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;">Jurusan Pendidikan Agama Kristen : Program Strata Satu (Terakreditasi), Program Strata Dua (Terakreditasi), Program Strata Tiga Doktor Teologi Konsentrasi PAK, Pelayanan Anak Kristen (D.1 Terapan)</li>
    <li style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;">Jurusan Teologi : Program Strata Satu (Terakreditasi) dan anggota PERSETIA, Ministri Penatua Gereja (D.1 Terapan)</li>
    <li style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;">Jurusan Pendidikan Musik Gerejawi : Program Strata Satu (Terakreditasi), Ministri Musik Gereja (D.1 Terapan)</li>
    <li style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;">Jurusan Pastoral Konseling : Program Strata Satu (Terakreditasi), Pemandu Wisata Rohani (D.1 Terapan), Kewirausahaan Kristen (D.1 Terapan)</li>
    <li style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;">Pendidikan Profesi Guru (PPG)</li>
</ol>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Kehadiran STAKPN Tarutung merupakan wujud nyata dari harapan dan doa umat Kristen yang sudah lama mendambakan kehadiran sebuah Perguruan Tinggi Agama Kristen dengan status Negeri. STAKPN Tarutung hadir untuk mempersiapkan mahasiswa menjadi hamba Tuhan yang setia, memiliki kedewasaan dan ketangguhan iman, berwawasan oikumenis, mampu menguasai ilmu sesuai dengan bidang ilmu yang dipelajari dan program studi yang diikuti dan ilmu penetahuan lainnya yang terkait, serta mampu mengembangkan dan memanfaatkannya untuk pelaksanaan tugas pelayanan gereja maupun tugas pengabdiannya di berbagai bidang kehidupan.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">STAKPN Tarutung juga melaksanakan pelayanan dibidang pendidikan tinggi untuk mencerdaskan kehidupan bangsa dengan mempersiapkan lulusan yang berkualitas, mandiri, kreatif, inovatif, dan mempunyai kerinduan melayani untuk mewujudkan masyarakat yang maju, sejahtera, adil dan makmur berdasarkan Pancasila dan UUD 1945. Dalam melaksanakan kegiatanyan memiliki strategi pengembangan jangka pendek dan jangka panjang untuk mengelola secara efektif kesempatan dan tantangan yang dihadapi.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Sejak STAKPN Tarutung dididirikan sudah banyak kerjasama yang sudah dilakukan untuk kemajuan dan pengembangan kampus baik tu dengan Instansi Pemerintah, dunia usaha, gereja, perguruan tinggi dalam dan luar negeri. Diantaranya adalah : Kerjasama dengan Pemerintah Kabupaten Tapanuli Utara, Toba Samosir, Samosir, Humbang Hasundutan, Tapanuli Tengah, Dairi, Gereja HKI, GKPI, GKPPD, GKI Sumut, GPP, GMB, Universitas Sumatera Utara, Universitas Negeri Medan, STGH HKBP, STT GMI Bandar Baru, STT GKLI, IHDN Denpasar, UHN Denpasar, GLFI Indonesia, Methodist Theologycal University, Hansei University South of Korea. Sehingga Percepatan alih status dari Sekolah Tinggi Agama Kristen Protestan Negeri (STAKPN) Tarutung menjadi Institut Agama Kristen Negeri (IAKN) Tarutung akan semakin terpacu dengan berbagai syarat yang telah terpenuhi oleh STAKPN Tarutung. Dibawah Kepemimpinan Prof. Dr. Lince Sihombing, M.Pd diharapkan akan membawa perubahan yang lebih baik bagi kampus STAKPN Tarutung, sehingga kampus STAKPN Tarutung merupakan Kampus yang akan siap berdaya saing baik di level nasional maupun di level Internasional.</p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;"><b style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px; font-weight: bold;">BEASISWA BIDIKMISI DAN PPA</b></p>
<p style="box-sizing: inherit; border: 0px rgb(230, 230, 230); outline: 0px; vertical-align: baseline;  margin: 0px 0px 20px; padding: 0px; line-height: 1.7; color: rgb(107, 107, 107); font-family: Poppins, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify;">Sejak Tahun 2015, STAKPN Tarutung sudah menyediakan Beasiswa Bidik Misi bagi para mahasiswa yang memilki prestasi di sekolah tetapi miskin dalam ekonomi. Pemberian beasiswa ini tentu saja ditentukan oleh beberapa persyaratan yang dibuat. Penentuan beasiswa ini juga harus turut serta berdasarkan bukti atau data yang faktual tanpa ada rekayasa, sehingga untuk memastikan itu selalu dibentuk tim untuk melakukan survey ke tempat masing-masing penerima beasiswa bidikmisi. Dan di Tahun 2016, STAKPN Tarutung melalui anggaran dari Pusat menyediakan beasiswa PPA untuk mahasiswa yang berprestasi dalam bidang Akademik. Ke depan STAKPN Tarutung akan lebih meningkatkan bidang akademik dengan menyediakan dan menambah kuantitas jumlah penerima beasiswa tersebut melalui lobi anggaran di pusat, sehingga dengan demikian minat masyarakat untuk menguliahkan anaknya di STAKPN Tarutung semakin tinggi.</p>
           
            </div>
        </div>
    </section>

    <section class="visi" id="visi">
        <div class="container">
            <h3>Visi dan Misi</h3>
            <div class="row">
                <div class="col">
                    <h4>Visi</h4>
                    <p>Pendidikan Berorientasi Pelayanan.</p>
                </div>
                <div class="col">
                    <h4>Misi</h4>
                    <p>Menghasilkan Sarjana yang Cerdas, Terampil dan Religius</p>
                </div>
            </div>
        </div>
    </section>

@endsection